---
name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        uses: actions/github-script@v6
        id: branch-name
        with:
          result-encoding: string
          script: |
            return (
            context?.payload?.pull_request?.head?.ref ||
            context?.payload?.ref
            ).replace("refs/heads/","");

      - name: Print branch name
        run: echo $BRANCH_NAME
        env:
          BRANCH_NAME: ${{steps.branch-name.outputs.result}}
